version: '3'
services:
  api:
    build: .
    restart: 'always'
    env_file: .env
    ports:
      - '8080:8080'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://127.0.0.1:8080/healthcheck']
    deploy:
      resources:
        limits:
          memory: '8G'
          cpus: '0.2'
    shm_size: '2G'
