version: '3'
services:
  api:
    restart: always
    environment:
      - ALLOWED_BOT_IDS=<bot-tokens>
      - TELEGRAM_API_HASH=<api-hash>
      - TELEGRAM_API_ID=<api-id>
      - EXTRA_ARGS=--local
      - PORT=8080
    ports:
      - '8080:8080'
    healthcheck:
      test: "curl --fail http://127.0.0.1:8080/healthcheck || exit 1"
    build: .

