# For local build and deploy
name: tgserver

services:
  api:
    build:
      context: .
      network: host
    env_file: .env
    restart: always
    ports:
      - '8080:8080'
    healthcheck:
      test: [CMD, curl, -f, 'http://127.0.0.1:8080/healthcheck']
    volumes:
      - file:/tmp/file

volumes:
  file: {}
