version: '3'
services:
  api:
    build: .
    restart: 'always'
    env_file: .env
    ports:
      - '8080:8080'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://0.0.0.0:8080/healthcheck']
    deploy:
      resources:
        limits:
          memory: '2G'
          cpus: '0.2'
    volumes:
      - file:/file
    shm_size: '2G'

volumes:
  file:
