name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

permissions: {}
jobs:
  checkout:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      new_update: ${{ steps.status.outputs.new_update }}
      new_version: ${{ steps.status.outputs.new_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Checkout for updates
        uses: actions/github-script@main
        id: status
        with:
          script: |
            const checkForUpdates = require('./scripts/check-for-updates');
            await checkForUpdates({ context, core, exec, github });
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    environment: Docker Hub
    needs: checkout
    steps:
      - name: Cache Docker layers
        uses: actions/cache@main
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@master
        with:
          platforms: linux/386,linux/amd64
          push: ${{ needs.checkout.outputs.new_update }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            tgserver/tgserver:latest
            tgserver/tgserver:${{ needs.checkout.outputs.new_version }}
