name: Docker Container to Fly.io

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  flyio:
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      FORCE_DEPLOY: ${{ secrets.FORCE_DEPLOY }} # optional
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Checkout upstream repo
        uses: actions/checkout@main
        with:
          repository: tdlib/telegram-bot-api
          path: telegram-bot-api
          submodules: recursive
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Cache
        uses: actions/cache@main
        with:
          path: ~/tmp/.cache
          key: ${{ runner.os }}-tg-server-${{ github.sha }}-flyio
      - name: Check for telegram-bot-api updates
        id: tg-update
        run: |
          if [[ "$FLY_API_TOKEN" != "" ]]; then
            make update
            IS_UPDATE=$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
            echo "deploy=$([ "${FORCE_DEPLOY:-false}" != "true" ] && echo $IS_UPDATE || echo "true")" >> $GITHUB_OUTPUT
            echo "commit=$IS_UPDATE" >> $GITHUB_OUTPUT
          else
            echo "deploy=false" >> $GITHUB_OUTPUT
            echo "commit=false" >> $GITHUB_OUTPUT
          fi
      - name: Deploying to Fly.io
        if: steps.tg-update.outputs.deploy == 'true'
        run: |
          flyctl deploy
      - name: Auto commit updates
        if: steps.tg-update.outputs.commit == 'true'
        run: |
            git config --local user.name "Github Action"
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Update telegram-bot-api submodules"
            git push origin main
