name: Deploy Docker Container to Heroku

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  heroku:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      FORCE_DEPLOY: ${{ secrets.FORCE_DEPLOY }} # Optional
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Checkout for updates
        uses: actions/github-script@main
        id: status
        with:
          script: require('./scripts/check-for-updates')({ context, core, exec, github });
      - name: Deploying to Heroku
        if: |
          steps.status.outputs.new_update == 'true'
            || steps.status.outputs.force_deploy == 'true'
        run: |
          if [[ "$HEROKU_API_KEY" != "" && "$HEROKU_APP_NAME" != "" ]]; then
            heroku container:login
            heroku container:push web -a $HEROKU_APP_NAME
            heroku container:release web -a $HEROKU_APP_NAME
          fi
      - name: Commit submodule updates
        if: steps.status.outputs.new_update == 'true'
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -am "Updated telegram-bot-api submodules" || echo "Nothing to commit"
            git push origin main
